cities = [
    "New York",
    "London",
    "Paris",
    "Tokyo",
    "Los Angeles",
    "Beijing",
    "Moscow",
    "Cairo",
    "Istanbul",
    "Sao Paulo",
    "Buenos Aires",
    "Sydney",
    "Rome",
    "Berlin",
    "Delhi",
    "Mumbai",
    "Mexico City",
    "Toronto",
    "Seoul",
    "Hong Kong",
    "Bangkok",
    "Jakarta",
    "Nairobi",
    "Dubai",
    "Copenhagen",
    "Madrid",
    "Stockholm",
    "Oslo",
    "Helsinki",
    "Singapore",
    "Dublin",
    "Amsterdam",
    "Vienna",
    "Athens",
    "Budapest",
    "Warsaw",
    "Prague",
    "Brussels",
    "Lisbon"
]